# Note: You should run a rake db:reset rather than rake db:seed in order to avoid
# 			getting duplicate data.


#--- Create some basic test players ---
players = Player.create([ 
	{name:'Kobe Bryant', 							twitter_handle: 'kobebryant', 			current_mentions: 0, bggif: 'http://i.giphy.com/q5hVhkKwKHDuo.gif',facts:['5x NBA Champion','2x Finals MVP','17x NBA Allstar'],nickname:'The Black Mamba', bio: "Kobe Bean Bryant (born August 23, 1978) is an American professional basketball player for the Los Angeles Lakers of the National Basketball Association (NBA). He entered the NBA directly from high school, and has played for the Lakers his entire career, winning five NBA championships. Bryant is a 17-time All-Star, 15-time member of the All-NBA Team, and 12-time member of the All-Defensive team. He has led the league in scoring twice, and he ranks third on both the league's all-time regular season scoring and all-time postseason scoring lists."},
	{name:'Lebron James', 						twitter_handle: 'KingJames', 				current_mentions: 0, bggif: 'http://i.giphy.com/7iMKNvnF4oVqM.gif',facts:['2x NBA Champion', '4x NBA MVP', '2x Olympic Gold Medals'],nickname:'King James',bio: "LeBron Raymone James (born December 30, 1984) is an American professional basketball player with the Cleveland Cavaliers of the National Basketball Association (NBA). Standing at 6 ft 8 in (2.03 m) and weighing 250 lb (113 kg), he has started at the small forward and power forward positions. James has won two NBA championships, four NBA Most Valuable Player Awards, two NBA Finals MVP Awards, two Olympic gold medals, an NBA scoring title, and the NBA Rookie of the Year Award. He has also been selected to 11 NBA All-Star teams, 10 All-NBA teams, and six All-Defensive teams, and is the Cavaliers' all-time leading scorer."},
	{name:'Carmelo Anthony', 					twitter_handle: 'carmeloanthony', 	current_mentions: 0, bggif: 'http://i.giphy.com/5BwrvWP19TdhS.gif',facts:['NCAA Champion','8x NBA Allstar', '2013 NBA Scoring Champion'],nickname: 'Melo', bio: "Carmelo Kyam Anthony (born May 29, 1984) is an American professional basketball player who currently plays for the New York Knicks of the National Basketball Association (NBA). Anthony attended Towson Catholic High School and Oak Hill Academy before playing college basketball at Syracuse. In Anthony's freshman season, he led the Orangemen to their first ever National Championship and was named the NCAA Tournament's Most Outstanding Player. Anthony then entered the 2003 NBA Draft where he was selected with the third overall pick by the Denver Nuggets."},
	{name:'Damian Lillard', 					twitter_handle: 'Dame_Lillard', 		current_mentions: 0, bggif: 'http://i.giphy.com/6cRLw4gAVzyXS.gif',facts:['NBA Rookie of the Year','2x NBA Allstar','24.5 ppg at Weber St.'], nickname:'Damian Thrillard',bio:"Damian Lamonte Ollie Lillard (born July 15, 1990) is an American professional basketball player for the Portland Trail Blazers of the National Basketball Association (NBA). Lillard is a 6 ft 3 in (1.91 m) point guard from Oakland, California who previously played for Weber State University. After being selected by Portland with the sixth overall pick in the 2012 NBA draft, he won the NBA Rookie of the Year by unanimous decision in his first season. Twice he has been named an NBA All-Star." },
	{name:'Kyrie Irving', 						twitter_handle: 'KyrieIrving', 			current_mentions: 0, bggif: 'http://i.giphy.com/xEwmyX7Y4jhm0.gif',facts:['USA Basketball Althlete of the Year', 'NBA Rookie of the Year', 'FIBA World Cup MVP'],nickname:'Uncle Drew',bio:"Kyrie Andrew Irving (born March 23, 1992) is an American professional basketball player for the Cleveland Cavaliers of the National Basketball Association (NBA). Irving was born in Melbourne, Australia but grew up in West Orange, New Jersey. He played collegiately at Duke University before being selected with the first overall pick in the 2011 NBA draft by the Cavaliers. Since being in the NBA, Irving has achieved a number of accolades including being the 2011–12 NBA Rookie of the Year and the 2014 NBA All-Star game MVP"},
	{name:'James Harden', 						twitter_handle: 'JHarden13', 				current_mentions: 0, bggif: 'http://i.giphy.com/zIZHSYB2Munvi.gif',facts:['Pac-10 Player of the Year','NBA Sixth Man of the Year','3x NBA Allstar'],nickname:'The Beard',bio:"James Edward Harden, Jr. (born August 26, 1989) is an American professional basketball player who currently plays for the Houston Rockets of the National Basketball Association (NBA). Harden played college basketball for Arizona State, where he was named a consensus All-American and Pac-10 Player of the Year in 2009. Harden was selected with the third overall pick in the 2009 NBA Draft by Oklahoma City and became the first player drafted in Oklahoma City Thunder franchise history.In 2012, he was named NBA Sixth Man of the Year with the Oklahoma City Thunder while helping them reach the NBA Finals. Harden was traded to Houston prior to the 2012–13 NBA season." },
	{name:'Chris Bosh', 							twitter_handle: 'chrisbosh', 				current_mentions: 0, bggif: 'http://i.giphy.com/6X7hnXX3CLynu.gif',facts:['2x NBA Champion','10x NBA Allstar','Toronto Raptors all-time Leading Scorer'], nickname: 'CB4',bio:"Christopher Wesson 'Chris' Bosh (born March 24, 1984) is an American professional basketball player who currently plays for the Miami Heat of the National Basketball Association (NBA). A high school 'Mr. Basketball' in Texas, Bosh left college at Georgia Tech after one season with the Georgia Tech Yellow Jackets men's basketball team to enter the 2003 NBA Draft. He was selected fourth overall by the Toronto Raptors in a very competitive draft class that included multiple future NBA superstars such as LeBron James, Dwyane Wade, and Carmelo Anthony. While at Toronto, Bosh emerged as one of the young stars in the league; he became a five-time NBA All-Star, was named to the All-NBA second team once, appeared for the US national team (with whom he won a gold medal at the 2008 Olympics), and supplanted former fan-favorite Vince Carter as the face and leader of the Raptors franchise." },
	{name:'Chris Paul', 							twitter_handle: 'CP3', 							current_mentions: 0, bggif: 'http://i.giphy.com/pLCrvfT2vJiKc.gif',facts:['NBA Rookie of the Year', '8x NBA Allstar','3x NBA Assists Leader'],nickname:'CP3',bio:"Christopher Emmanuel 'Chris' Paul (born May 6, 1985) is an American professional basketball player for the Los Angeles Clippers of the National Basketball Association (NBA). Standing at 6 ft 0 in (1.83 m) and weighing 175 lb (79 kg), he has started exclusively at the position of point guard. Paul has won the NBA Rookie of the Year Award, an Olympic gold medal, and led the NBA in assists three times and steals six times. He has also been selected to eight NBA All-Star teams, six All-NBA teams, and six All-Defensive teams."},
	{name:'Blake Griffin',						twitter_handle: 'blakegriffin31',   current_mentions: 0, bggif: 'http://i.giphy.com/oUVWSw2gW1BT2.gif',facts:['NBA Rookie of the Year', '5x NBA Allstar', 'Slam Dunk Contest Champion'],nickname: 'High Griffinition',bio:"Blake Austin Griffin (born March 16, 1989) is an American professional basketball player who currently plays for the Los Angeles Clippers of the National Basketball Association (NBA). He played college basketball for the Oklahoma Sooners, when he was named the Consensus National Player of the Year as a sophomore. Griffin was selected first overall by the Clippers in the 2009 NBA draft, and is a five-time NBA All-Star and a three-time All-NBA Second Team selection." },
	{name:'Pau Gasol', 								twitter_handle: 'paugasol', 				current_mentions: 0, bggif: 'http://i.giphy.com/HbhaY0Lv23Ztu.gif',facts:['2x NBA Champion','Memphis Grizzlies all-time leading scorer','2x Europe Player of the Year'],nickname:'Kung Pau',bio:"Pau Gasol Sáez (born July 6, 1980) is a Spanish professional basketball player who currently plays for the Chicago Bulls of the National Basketball Association (NBA). He is a five-time All-Star, and a three-time All-NBA selection, once on the second team and twice on the third team. He has won two NBA championships, both with the Los Angeles Lakers. He was the NBA Rookie of the Year in 2002 with the Memphis Grizzlies, the only non-American NBA player to win that award. He is the older brother of fellow NBA player Marc Gasol." },
	{name:'Jeremy Lin', 							twitter_handle: 'JLin7', 						current_mentions: 0, bggif: 'http://i.giphy.com/QALZi6c0wDBrq.gif',facts:['ABA Club Championship MVP', '2x First-team All-Ivy Leauge','1x Second-team All-Ivy Leauge'],nickname: 'Linsanity',bio:"Jeremy Shu-How Lin (born August 23, 1988) is an American professional basketball player for the Los Angeles Lakers of the National Basketball Association (NBA). He unexpectedly led a winning turnaround with the New York Knicks in 2012, which generated a global following known as 'Linsanity.'"},
	{name:'Derrick Rose', 						twitter_handle: 'drose', 						current_mentions: 0, bggif: 'http://i.giphy.com/PPGnuh9nCr2PS.gif',facts:['NBA MVP','NBA Rookie of the Year', '3x NBA Allstar'],nickname:'Drose',bio:"Derrick Martell Rose (born October 4, 1988) is an American professional basketball player who currently plays for the Chicago Bulls of the National Basketball Association (NBA). He played one year of college basketball for the University of Memphis before being drafted first overall by Chicago in the 2008 NBA draft. Rose became the first guard to be drafted first overall in the NBA draft since Allen Iverson in 1996 and would subsequently win NBA Rookie of the Year. In 2011, Rose was named the NBA Most Valuable Player, becoming the youngest player to win this award at 22 years and 6 months old"},
	{name:'Kevin Durant',							twitter_handle: 'KDTrey5',					current_mentions: 0, bggif: 'http://i.giphy.com/cPNPvEayD2yo8.gif',facts:['NBA MVP','National College PLayer of the Year','6x NBA Allstar'],nickname:'The Durantchula',bio:"Kevin Wayne Durant (born September 29, 1988) is an American professional basketball player with the Oklahoma City Thunder of the National Basketball Association (NBA). Standing at 6 ft 9 in (2.06 m) and weighing 240 pounds (109 kg), he has played the small forward and power forward positions for the Thunder, formerly the Seattle SuperSonics. Durant has won an NBA Most Valuable Player Award, four NBA scoring titles, the NBA Rookie of the Year Award, and an Olympic gold medal. He has also been selected to five All-NBA teams and five All-Star teams."},
	{name:'Stephen Curry',						twitter_handle: 'StephenCurry30',		current_mentions: 0, bggif: 'http://i.giphy.com/bAWxvR83iVWYo.gif',facts:['NCAA Division 1 Scoring Leader','2x NBA Allstar','All-NBA Second Team'],nickname:'member of the splash brothers',bio:"Wardell Stephen 'Steph' Curry II (born March 14, 1988) is an American professional basketball player who currently plays for the Golden State Warriors of the National Basketball Association (NBA). Listed at 6 ft 3 in (1.91 m) and 190 lb (86 kg),A two-time NBA All-Star, Curry plays mostly at point guard. He is the son of former NBA player, Dell Curry."},
	{name:'Dwight Howard',						twitter_handle: 'DwightHoward',			current_mentions: 0, bggif: 'http://i.giphy.com/gIHB6S5PuZeZG.gif',facts:['8x NBA Allstar','5x NBA Rebounds Leader','3x NBA Defensive Player of the Year'],nickname:'Superman',bio:"Dwight David Howard (born December 8, 1985) is an American professional basketball player for the Houston Rockets of the National Basketball Association (NBA). Howard, who plays center, had an outstanding high school career at Southwest Atlanta Christian Academy. He chose to forgo college and entered the 2004 NBA Draft, and was selected first overall by the Orlando Magic. An eight-time All-Star, seven-time All-NBA team selection, five-time All-Defensive member, and three-time Defensive Player of the Year, Howard has been ranked consistently as one of the best in the league in rebounds, blocks, field goal percentage and free throw attempts, and has set numerous franchise and league records. He led the Magic to three division titles and one conference title, and he was the winner of the 2008 NBA Slam Dunk Contest. He is now with the Houston Rockets in 2013."},
	{name:'John Wall',								twitter_handle: 'JohnWall', 				current_mentions: 0, bggif: 'http://i.giphy.com/9QwlSdAZ8ubqo.gif',facts:['2x NBA Allstar','SEC Player of the Year','NBA All-Rookie First Team'],nickname:'Optimus Dime',bio:"Johnathan Hildred Wall, Jr. (born September 6, 1990) is an American professional basketball point guard with the Washington Wizards of the National Basketball Association (NBA). A Raleigh, North Carolina native, Wall was chosen first overall in the 2010 NBA draft by the Wizards after playing one year at the University of Kentucky. He is a two-time NBA All-Star."}
])


#--- Add some random hourly scores for today for each player ---
#note: these scores will be all over the place since it's just using rand(1000)
today = Time.now.yday
start_day = today - 30

# puts "adding hourly scores for each player for today"
# Player.all.each do |p|

# 	24.times do |ii|
# 		score = rand(1000) + 1
# 		p.hourly_scores << HourlyScore.create(yearday: today, hour: ii, score: score)
# 	end

# 	puts "done with #{p.name}"

# end

#--- Create some random ass total mentions that in no way correspond to anything ---
puts "adding total mentions"

# 24.times do |ii|
# 	TotalMention.create(yearday: today, hour: ii, total_mentions: rand(5000))
# end

@hour = Time.now.hour
@day = Time.now.yday



TotalMention.create ([
	{total_mentions: 5, yearday: @day, hour: @hour}
	])




